// HTTP FILE TO TEST REQUESTS

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "${userID1}"
}

